### ISSUE TITLE
Explore tool not showing object for a particular case.

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#10]
(this happens in production Skyserver as well)
After visiting the chart or navigate pages for the first time, we have the option of opening the explore link (on the upper right hand side), presumably concerning the object in the center of the image. After clicking it, explore opens with this error message: 
"The object corresponding to the id specified does not exist in the database.
Please try another object"

Explore should instead display the object that was being displayed on navigate or the chart. Note that explore's search parameters are ra and dec.

**Comment by mtaghiza** [comment]
Turns out that the default values of the image center (visualRA,visualDEC) defined in web.config are about 1.7arcsec farther than the actual center of the object that comes as default when opening the "chart" or "navigate" for the first time. 

On the other hand, explore only looks for objects within a radius of 0.5arcsec from the given (RA,DEC). 

That is the reason why the default object is missed.

The easiest solution is to change the values to 
(visualRA,visualDEC) = (179.689293428354,-0.454379056007667)

But still remains the issue of increasing the search radius in explorer from 0.5arcsec to something bigger. This will not harm, since will always return the closest one, although fro a little longer database search time.

**Comment by raddick** [comment]
So the solution to this would be to make that change in the Web.config file?

Could you assign this issue to yourself, implement the fix on skydev, and then close the issue?

This change is a little more complicated than usual because Web.config is not managed through git. Ask Mitya and/or Ani what the right procedure is.

**Comment by mtaghiza** [comment]
Changing the web.config is not a problem. What we might have to discuss is the 0.5arcsec restriction. 
If the user eventually types in the (RA,DEC) with lower precision, the explore tool can possibly never return an object and the user might think that there is nothing there.

**Comment by raddick** [comment]
Thanks! That the user might think that there is nothing there would be a much, much bigger problem. All our educational projects use RA/dec rounded to 3 decimal places, and it will never occur to educational users to try additional precision (and indeed, why should it?).

I have never run into this problem with our default 0.5 arcsec radius, so I'd strongly advocate leaving it as-is. Labeling this issue with "question" in case you (Manu) or others want to discuss further.

Go ahead and fix the default position in Web.config, however.

**Comment by mtaghiza** [comment]
chose just to change the Web.config file. Closing this issue.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
