### ISSUE TITLE
Search by 5-part SDSS ID: error msg for inputs of wrong type is cut off

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#101]
In the Quick Look tool:

`http://scitest02.pha.jhu.edu/SkyServer/en/tools/quicklook/summary.aspx`

Click on "Search by... 5-part SDSS".

Enter a value that does not fit the proper 5-part pattern, e.g. see below.

The tool returns an alertbox saying:

`SDSS Id has 5 parts, Run-Rerun-Camcol-Field-Obj`

That is actually a very good thing! Yay!

The bug is that in Chrome 44 and IE 11, the alertbox is confined to the underlying popup window, and so the edges of the error message are cut off.

Example of the input that triggers the bug:

![test1](https://cloud.githubusercontent.com/assets/1709156/9446235/71ad0efc-4a5e-11e5-9673-80f9397e646b.jpg)

Bug behavior:

![test2](https://cloud.githubusercontent.com/assets/1709156/9446242/7719e572-4a5e-11e5-98ca-872c01578455.jpg)

**Comment by mtaghiza** [comment]
This will no longer show, since these search windows have been changed, showing instead the search window present in the Explore tool. Closing...
