### ISSUE TITLE
Explore: non-numeric input for ra/dec returns error

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#102]
In the Explore tool:

`http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/summary.aspx`

Click Search. Search textboxes appear at the top of the page, one of which says RA/Dec.

Enter non-numeric values for ra/dec. The tool returns a general error message saying:

`A problem has occurred in the Explore tool. Please inform helpdesk@sdss.org.`

Triggering input:

![test3](https://cloud.githubusercontent.com/assets/1709156/9446583/73491ca4-4a60-11e5-95a1-b1f5bb8a5b21.jpg)

Behavior:

![test4](https://cloud.githubusercontent.com/assets/1709156/9446586/7790b8c6-4a60-11e5-9f56-4f450cc4bd75.jpg)

**Comment by mtaghiza** [comment]
It seems that this error message is correct, and appears as well in the production DR12.

**Comment by mtaghiza** [comment]
Fixed.
