### ISSUE TITLE
Explore: Bad input for plate-mjd-fiber returns error message

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#103]
In the Explore tool Search window, results from entering any erroneous values of plate-mjd-fiber - this includes out-of-range numeric values as well as non-numeric values.

Error message returned is the same as in issue #102.

**Comment by mtaghiza** [comment]
It seems that this error message is correct, and appears as well in the production DR12.

**Comment by mtaghiza** [comment]
Fixed
