### ISSUE TITLE
Explore: interactive spectrum still points to DR10

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#104]
See the Explore tool, click on "Interactive Spectrum." Should point to the data release specified in that site's globals configuration.

**Comment by mtaghiza** [comment]
Could you be more specific? 
The link opens 
http://dr12.sdss3.org/irSpectrumDetail?locid=4128&commiss=0&apogeeid=2M13102744+1826172
which is DR12.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by thakar** [comment]
Fixed in v1_3_0
