### ISSUE TITLE
Explore: "Other observations" link fails to find other observations

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#105]
In the Explore tool, click on Other Observations. It shows a page labeled "Other photometric observations (detections)". The page displays correctly, but we also want to check whether it is displaying the correct data.

Here's how it's supposed to work: If you search for an object that has an object ID connected to a thing ID, and that thing ID has other object IDs connected to it, that page will show all those other object IDs. (They are other observations of the same "thing").

But it appears to show only the single observation you looked for to begin with, and "Other observations of this thing" always shows "No data found for this object".

This happens even when after I ran a query to purposely select thingIDs with more than one associated objID.

**Comment by mtaghiza** [comment]
Fixed. Will work correctly in next version.

**Comment by thakar** [comment]
Fixed in v1_3_0
