### ISSUE TITLE
Menu overlap between crossID and SkyQuery cross-match

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#106]

**Comment by mtaghiza** [comment]
Fixed. Will show correctly in next version.

**Comment by raddick** [comment]
Thanks! Is the fix checked in to GitHub in the sciserver_vm branch?

**Comment by mtaghiza** [comment]
No, its on dev. Will check the changes into sciserver_vm on thursday and then replace test with the new version.

**Comment by thakar** [comment]
Fixed in v1_3_0
