### ISSUE TITLE
Explore: No PhotozRF link

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#112]
Test s_explore_19 says "click on the PhotozRF link". But there is no PhotozRF link! See:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/summary.aspx

I'm not sure whether this is a missing feature - a link that should be there but isn't - or a test script problem - a test that no longer applies in this release.

Manu, could you please investigate? Tagging with "question" for now. Please tag with either "bug" or "fixtestscript" and fix. Thanks!

**Comment by mtaghiza** [comment]
Turns out that the PhotozRF table does not exist anymore in the newest schema. I might have been looking at the Explore of an early data release that had this option enabled. 

Just erased this test on the master testing spreadsheet.

Closing this issue...
