### ISSUE TITLE
Explore: clicking on "Cross-ID" in left column should auto-show the Cross-ID section

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#113]
On the Explore tool, right now when you click the Cross-ID link in the left-hand column, the main window/frame jumps to put the cross-identifications section on top. As it should. But the section content remains hidden until the user clicks Show.

If the user has clicked Cross-ID in the left column, that is an indication that they would like to see the cross-ID information. So we should auto-show the results.

**Comment by mtaghiza** [comment]
Fixed. Will show in next version.

**Comment by raddick** [comment]
Fixed!
