### ISSUE TITLE
Invalid rectangular search values in IQS result in unhelpful, mishandled error message

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#118]
If you enter invalid values for the rectangular search option in the Imaging Query Form (IQS), e.g., dec values of 0.2 and -0.2 (second value less than first), the error is not properly handled and results in the following cryptic error message:

SQL returned the following error: 
Failed to execute a query: Incorrect syntax near 'Illegal'. Incorrect syntax near 'pERROR:'.

**Comment by mtaghiza** [comment]
Fixed.
