### ISSUE TITLE
SkyServer: Unnecessary Login Button Message

### ISSUE THREAD

**Issue by jkim485** [idies/SkyServer#12]
When I clicked the "Login" button on the RHS floaty of the SkyServer Home Page, I got a pop-up saying: "The page at scitest02.pha.jhu.edu says: http://scitest02.pha.jhu.edu/SkyServer/en/home.aspx" and then I click 'OK' and then it takes me to the Portal.

**Comment by raddick** [comment]
This was probably a debug message that was left over from a prior version. Jordan is investigating how to fix.

**Comment by raddick** [comment]
On second thought... let's leave this be for the moment. We're still testing the connection between the login portal and SkyServer (see issue #13), so an alert saying what portal we're jumping to will be helpful.

**Comment by raddick** [comment]
Now that SkyServer is properly connected to the new portal, let's go ahead and remove this message.

**Comment by mtaghiza** [comment]
Fixed. Removed the alert message. Will work correctly in the next version.
