### ISSUE TITLE
API page: clicking on Radial & Rectangular links gives key error

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#120]
On the API page, when the user clicks on the links in either "Radial" or "Rectangular" sections (link below):

http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/api.aspx#search

A new window opens returning the error, "The given key was not present in the dictionary."

Could this be a problem due to the keystone info not being sent with the API request?

**Comment by mtaghiza** [comment]
Fixed
