### ISSUE TITLE
Problem running search forms when logged-in with keystone

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#13]
Can't run the searches when logged-in (e.g. radial search). However, they run fine when logged-out.

**Comment by raddick** [comment]
Is this still an issue in the sciserver_v1_0_1 version? If so, please add the label "sciserver_v1_0_1" to this issue.

**Comment by raddick** [comment]
Manu has been investigating this. Assigning to him. Manu, if someone else is working on it instead, please reassign to them.

**Comment by raddick** [comment]
It's still giving a "given token is not authorized" error as of sciserver_v1_2_0 .

I'm calling this a showstopper. Yes, I know you can run queries as an anonymous user, but you can do that already on the production skyserver. The new functionality we're adding as part of the SciServer project requires that logged-in users also be able to run queries.

**Comment by mtaghiza** [comment]
Fixed. The problem was a wrong URI used for logging to keystone in the web.config file.
Will be working properly in the next version.
