### ISSUE TITLE
Portal callback URL could not be parsed

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#131]
Easiest to explain with a screenshot. Note the error message it gives and the URL that partially shows in the URL bar.

The result of this behavior is that the user doesn't get redirected to SkyServer after login.

Encountered on Firefox 41 on the Mac Yosemite OS, if that matters.

<img width="1320" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/1709156/10393620/6c8efef6-6e5f-11e5-93e2-bd92de32c91a.png">

**Comment by mtaghiza** [comment]
Fixed. Correct call-back URL will appear in version right after sciserver-v1.5.1

**Comment by mtaghiza** [comment]
Also, when the user logs out, the page is redirected to the login-portal. Is that what we want or should the page stay in skyserver? seems that the first option gives the advantage of showing/advertising to the users all other sciserver components, which might be better.

**Comment by raddick** [comment]
HOWEVER, upon further reflection, I think this is actually a showstopping bug. It means that the user can create a new login portal account, but can't log in with that account the next time they visit the site. When they get the Invalid URI message and can't easily get back to SkyServer, they're likely to leave and not come back.

@mikear69 can overrule me on this, but I think I'm going to add a "showstopper" label here, and create a new milestone for a v1_5_2 version that will fix this bug.

**Comment by mtaghiza** [comment]
IMO, I would not stop testing just for this.

**Comment by mtaghiza** [comment]
You can try again. Just uncommented a line in the we.config file. This is probably not worth a new release.

**Comment by raddick** [comment]
Excellent! Glad to hear it, especially to hear the problem was fixed in 
web.config . This is definitely not worth stopping testing for. I'll 
remove the v1_5_2 milestone and we'll get this tested for the v1_6_0 
milestone. I'll also remove the showstopper.

This also means that we should be extra-careful to move the web.config 
file(s) when we push to production.

~Jordan

**Comment by raddick** [comment]
Fixed, so closing. But see issue #167 for a different problem with the same feature.
