### ISSUE TITLE
"SDSS Outlines" and "SDSS Bounding Boxes" fails in Navi tool

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#134]
Happens in all browsers. See screenshot:

<img width="974" alt="untitled-3" src="https://cloud.githubusercontent.com/assets/1709156/10400168/249f4aee-6e85-11e5-8cd3-788bf1e3b5c2.png">

**Comment by mtaghiza** [comment]
The problem is that the query fails when sent to casjobs for execution. Haven't tried to debug yet, but after Deoyani's refactoring, the query will be sent directly to the database and we'll not have that porblem. (query executes with no problem in SSMS)

**Comment by raddick** [comment]
@mtaghiza , will there be changes necessary to SkyServerWS as well? If so, I'll file the same issue there.

**Comment by mtaghiza** [comment]
Can't reproduce this problem anymore. Probably due to change in config file.
