### ISSUE TITLE
Dec should process out-of-range values differently from RA

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#136]
When a user enters an RA range greater than 360 or less than 0, our visual tools correctly wrap around the sky by changing the value x to abs(x mod 360) or whatever (that's my educated guess of how the code works - the important thing is it works correctly AFAIK.

But the same behavior occurs when a user enters a dec greater than 90 or less than -90, which is incorrect. What should actually happen is that if the user-entered value should be replaced with 90; if the user-entered value is less than -90, it should be replaced by 90.

I think this is fairly easy to fix. Assigning to Manu.

**Comment by mtaghiza** [comment]
That is the desired behavior, as it was asked by Ani. In fact it was changed to this stage in order to be consistent with other standard online tools. This behavior is also consistent with the way image cutout wraps Dec values. Please, talk to Ani to discuss further, or verify that it works correctly and close.

**Comment by raddick** [comment]
Cool, I'll check with Ani and possibly close the ticket.

~Jordan

**Comment by mtaghiza** [comment]
An example from Simbad:
searching RA=360.020612795536 DEC=180.430720
returns a galaxy at RA=179.689293428354 DEC=-0.454379056007667

Link:

http://simbad.u-strasbg.fr/simbad/sim-coo?Coord=360.020612795536+180.430720&CooFrame=FK5&CooEpoch=2000&CooEqui=2000&CooDefinedFrames=none&Radius=2&Radius.unit=arcsec&submit=submit+query&CoordList=

**Comment by raddick** [comment]
After investigating Simbad and talking with an observational astronomer (Adam Bolton), I'm convinced that we are doing this the right way. Marking as invalid and closing.
