### ISSUE TITLE
Use different symbols for APOGEE spectra and query matches in Finding Chart

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#137]
In the Finding Chart, we have the ability to mark objects that match some queries. These are marked in the image with upside-down purple triangles. The problem is that APOGEE spectra are also marked with upside-down triangles. The APOGEE triangles are white rather than purple, but it's not good web practice to provide information using color alone. It's confusing for all users, but deal-breaking for colorblind users.

Choose a different symbol for the query marking. Self-assigning.

**Comment by raddick** [comment]
P.S. Here's a screen shot with both shape/color symbols visible.

<img width="713" alt="untitled-4" src="https://cloud.githubusercontent.com/assets/1709156/10402944/56e7c3da-6e96-11e5-876d-c065664b3484.png">

**Comment by mtaghiza** [comment]
Could we send this suggestion directly to Deoyani? she's currently in charge of refactoring the image cutout code.

**Comment by raddick** [comment]
Is the code to generate the triangles part of the SkyServer code, or is 
it part of the ImgCutout code?

~Jordan

**Comment by mtaghiza** [comment]
part of image cutout, which is part of SkyserverWS


________________________________

**Comment by raddick** [comment]
Got it. I'll close the issue here and open it in skyserverWS.

~Jordan

**Comment by raddick** [comment]
Filed in the SkyServerWS issues, closing here.
