### ISSUE TITLE
SQL query/SAS upload option not shown in Radial, Rectangular and SQL search, imaging query, spectroquery and IR spectroquery 

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#14]
Test: s_rad_search_2, s_rect_search_2, s_sql_search_2, s_imaging_query_form_2, s_spectro_query_form_2 and s_irspectro_query_form_2

After running them, the result set is only a table. Missing are the sql queries that where executed to get those tables, as well as the option of uploading the objects to SAS.
Also, the default format for the result-set is generally 'csv' instead of 'html'.

**Comment by mtaghiza** [comment]
The solution is to build the html text in the SkyserverWS, and then send it to SkyServer.

**Comment by mtaghiza** [comment]
Finished the code that build up the html text on SkyServerWS. 

Now the Radial search works as before.

**Comment by mtaghiza** [comment]
All fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Verified that the SQL query shows and that the Submit button next to "Upload to SAS" is working.

Upload to SAS features don't appear on the Infrared Spectra Query Form, but they don't appear on the form on the production SkyServer either.

So I'm declaring this verified-as-fixed as of sciserver_v1_2_0. Closing issue.
