### ISSUE TITLE
Set maximum number of rows retrieved to 5e5 across all web form searches

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#15]
Tests: s_rad_search_13, s_rect_search_13, s_search_form_12, s_sql_search_12, s_imaging_query_form_8, s_imaging_query_form_9, s_spectro_query_form_8, 
s_spectro_query_form_9, s_irspectro_query_form_8 and s_irspectro_query_form_9

This number is inconsistent, taking values of 50000,100000 or 500000 depending on the web-form (sql search, imaging search, spectro search, etc). Could change all of them to 500000.
Sometimes the resultset does not show (e.g., s_imaging_query_form_9)

**Comment by raddick** [comment]
Thought from Sue: just trim after the first semicolon.

Check spExecuteSQL for details of how this works.

**Comment by mtaghiza** [comment]
All fixed. The limit is enforced in SkyserverWS, when wrapping the sql query inside SpExecuteSQL. Correct behavior will show in next version.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015.

I did a quick check by running "select objid,ra,dec from photoobj" in the SQL Search tool and returning as CSV. I opened the CSV to verify that, as it should, it returns 500k rows.

Closing the issue.
