### ISSUE TITLE
Hide link to SkyQuery CrossMatch for now

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#16]
Since SkyQuery CrossMatch is not fully ready yet, have to hide the link to it from the SkyServer homepage.

**Comment by mtaghiza** [comment]
done. Closing...

**Comment by raddick** [comment]
And now that the SkyQuery cross-match *is* working (as of sciserver_v1_2_0), the link has properly been restored to the home page. Thanks!
