### ISSUE TITLE
Permission/security issue with spExecuteSQL stored procedure

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#17]
Just adding for completeness this problem known by all: SkyServer user can't run queries into Casjobs since it does not have permissions to insert into tables in WEBLOG database (through execution of spExecuteSQL stored procedure that parses and checks the users' query).

**Comment by mtaghiza** [comment]
Solved by executing insert commands as a new user. Sue created the new script and user in the database server. We must make sure that these modifications are recorded somewhere and repeated for next releases.

**Comment by raddick** [comment]
Manu, could you please verify that this is still working in sciserver_v1_2_0?

And did we record this to make sure we repeat is for future releases as well?

Reopening and marking as "needstest" and "question".

**Comment by raddick** [comment]
Is this working in sciserver_v1_4_0? I'd test it myself, but not sure how to.
