### ISSUE TITLE
Default image does not load when opening Chart for the first time

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#18]
Test s_chart_1:

when clicking directly to the link

http://scitest02.pha.jhu.edu/Skyserver/en/tools/chart/image.aspx

, the default image does not load (shows a broken image icon). However, following the link from the skyserver homepage or clicking in "get image" button work with no problem.

**Comment by mtaghiza** [comment]
Seems that this page was never intended to be accessed through this link (same thing happens in the production skyserver). The image appears as soon as "get image" is pressed.
Closing...

**Comment by raddick** [comment]
I think this is OK, since we never intended the chart page to be opened directly onto the image.aspx page. So I think this is not really a bug. For our issue tracking, it should be marked as "Invalid" instead. Marking is as "Question" for now, and reopening, so we can discuss this.

**Comment by mtaghiza** [comment]
Invalid issue. Closing...
