### ISSUE TITLE
Image list tool takes long time to load images

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#19]
Test s_imglist_2:
clic on
http://scitest02.pha.jhu.edu/Skyserver/en/tools/chart/list.aspx
and press get image. Takes much longer time compared to the DR12 production website.

**Comment by mtaghiza** [comment]
Seems that this could be a Casjobs issue. When debugging the ImageCutout from SkyServerWS, we noticed that there is a long lag between sending the queries to Casjobs REST and retrieving the result-set back. Note that this is not a database problem, since the same type of queries were executed in MS SQL Server management studio, and took little time to return result-sets.

**Comment by mtaghiza** [comment]
Fixed. Mitya change serialization format in casjobs. Now loads much faster. Will show up in next version.

**Comment by raddick** [comment]
Not sure exactly how slow it was before, but it seems fine now. Checked with link below. Closing ticket.

Verified as working in sciserver_v1_2_0 as of 8/18/2015
