### ISSUE TITLE
Image list tool does not mark objects with spectra

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#20]
Test s_imglist_6:
option S (objects with spectra) does not work

**Comment by mtaghiza** [comment]
Caused by a change of the schema in the views. The view 'specobj' was giving the wrong values for 'ra' and 'cx', making the finding of objects impossible. All the views were recreated, and now it works.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
