### ISSUE TITLE
Clicking id info of objects does not work (Image List tool)

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#21]
Test s_imglist_7:
After clicking on the id info on the top of each object, I get:

"The object corresponding to the id specified does not exist in the database.
Please try another object."

**Comment by mtaghiza** [comment]
This happens because the search radius in the explore tool is 0.5'' (hardcoded). Therefore, if the objects' RA,DEC are only given with 3 decimal points of accuracy, explore will miss the objects. Had to set it back to search radius = globals.EqSearchRadius (=0.75'=45'') and now it does not miss any object.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
