### ISSUE TITLE
Broken "Fit Parameters" link in Explore tool

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#23]
Test s_explore_30:
link:

http://scitest02.pha.jhu.edu/Skyserver/en/tools/explore/parameters.aspx?id=1237668296598749280&spec=2947691243863304192&apid=apogee.apo25m.s.stars.4128.2M13102744+1826172&field=0x112d14c220880000

**Comment by raddick** [comment]
The problem is in the parameters.aspx file.

**Comment by mtaghiza** [comment]
Fixed parameters.aspx. The RunCasJobs was missing a second parameter. Not closing for now until it is tested.

**Comment by raddick** [comment]
Seems to be working fine in sciserver_v1_2_0:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/parameters.aspx?id=1237668296598749280&spec=2947691243863304192&apid=apogee.apo25m.s.stars.4128.2M13102744+1826172&field=0x112d14c220880000

Closing issue.
