### ISSUE TITLE
Pressing Reset button clears up all values instead of bringing up original values in Rectangular Search form

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#29]
Test: s_rect_search_16

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/rect.aspx

Closing.
