### ISSUE TITLE
Using extreme input paramaters does not bring up a "no objects found" warning nor error in Radial and Rectangular search forms

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#30]
Tests: s_rad_search_15, s_rad_search_16 and s_rect_search_15

**Comment by raddick** [comment]
What extreme input parameters did you use to test? What do the forms do instead of what they should do?

**Comment by mtaghiza** [comment]
e.g. ra outside [0,360] and dec outside [-90,90]
We can always compare to the results obtained by running the same procedure in the production skyservers.

**Comment by mtaghiza** [comment]
This is issue is now fixed, but will be available in the next version

**Comment by raddick** [comment]
Fixed in sciserver_v1_2_0

Returns error message helpful to user
