### ISSUE TITLE
SDSS footprint button not working in Search form

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#31]
test: s_search_form_8

**Comment by raddick** [comment]
This seems like a lower-priority bug? Ani, what are your thoughts?

**Comment by thakar** [comment]
Agreed, although if it is easy to fix, it should be fixed.

    Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by mtaghiza** [comment]
Not that easy to fix, but succeeded...:)
Rewrote the radial search query in SkyServerWS and wrote a costume HTML response for SkyServer
closing...

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
