### ISSUE TITLE
Proximity search not working in imaging and spectro query form

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#33]
test: s_imaging_query_form_14, s_imaging_query_form_15, s_imaging_query_form_16
All give a runtime error.

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Looks to be working in sciserver_v1_2_0:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/IQS.aspx

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/SQS.aspx
