### ISSUE TITLE
No reultset returned in SpectroQuery

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#35]
Tests: s_spectro_query_form_1 to s_spectro_query_form_17
Probably the back-end was not working properly when this test was run. Must rerun these tests and see if it works.

**Comment by mtaghiza** [comment]
Fixed. Normal behavior will show in next version.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/SQS.aspx
