### ISSUE TITLE
Repeated flags in 2 different windows in IR spectro query

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#36]
Test: s_irspectro_query_form_16

The flags under Targeting Flags #2
(APOGEE_TARGET2) are the same as the flags under Targeting Flags #1
(APOGEE_TARGET1) and there is a ""\n"");"" string on the box.

**Comment by mtaghiza** [comment]
The same returned dataset variable was being used to show both windows. Changed to a new one. Now working. Closing...

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
