### ISSUE TITLE
Imaging and Infrared Spectra sections not shown in results pane of Radia/Rectangular search

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#37]
The output for the Radial and Rectangular search forms should be divided into two sections when HTML output format is selected, with the titles "Imaging" for the imaging results and "Infrared Spectra" for the APOGEE matches.

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by thakar** [comment]
Fixed in v1_3_0
