### ISSUE TITLE
Choosing either galactic or equatorial coordinated does not change resultset in Radial, Rectangular and IR spec query forms

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#43]
For example, selecting (RA=0,DEC=0) in equatorial coordinates gives the same result as selecting (l=0,b=0) in galactic coordinates.

**Comment by mtaghiza** [comment]
This might be a problem with SkyserverWS itself.

**Comment by raddick** [comment]
Do we know whether this bug happens in SkyServer, or in SkyServerWS, or in both?

If it's just in SkyServerWS, please close it here and tag with "invalid," and file a new issue in SkyServerWS.

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Update: as of sciserver_v1_2_0 , it is working for the radial and rectangular search tools, but **not yet working** for the Infrared Spectra Query Form.

Manu (@mtaghiza), has the fix been implemented, to come in the sciserver_v1_3_0 release?

Either way, I'm labeling as "needstest" for now. If it still needs to be fixed, please remove the "needstest" label until it's fixed. Thanks!

**Comment by raddick** [comment]
Update: it works! I got tricked by the fact that the ra/dec listed and the l/b listed are actually for the same point.

Thus, verified as working in sciserver_v1_2_0.
