### ISSUE TITLE
Check Syntax option missing in query forms

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#44]
The option to check the query syntax is missing in the form queries (Radial, Rectangular, SQL Search etc.)

**Comment by mtaghiza** [comment]
Done. Added the syntax check to the SqlSearch component of SkyServerWS. In Skyserver, only  SQL Search and Search Form seem to ha a syntax button. Clicking this button now checks for syntax.
Closing...

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
