### ISSUE TITLE
Entering syntactically incorrect SQL query gives a runtime error

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#45]
If I enter a "#" between 2 queries in the SQL Search form and press Submit, I get a runtime error page :"Server Error in '/SkyServer' Applicaton".

**Comment by raddick** [comment]
Ani, what is the desired behavior here?

**Comment by raddick** [comment]
Still not working in sciserver_v1_2_0. Try with the following:

`select top 10 * from photoobj`
`#`
`select top 20 * from photoobj`

Returns the unhelpful error message:

`SQL returned the following error:`

I think this is related to issue #82.

**Comment by raddick** [comment]
See update in #82. Should we close this issue and discuss further there?

**Comment by raddick** [comment]
I'm going to close this and we can continue this discussion under issue #82.
