### ISSUE TITLE
SQL Search produces an empty FITS output file

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#46]
If I select FITS output option on the SQL Search page and press Submit, a FITS file is saved but it is empty (no binary table in it).

**Comment by mtaghiza** [comment]
the reason is that the default query contains the column "class" of type varchar. The new fits library does not handle this type for now, that's why the output is empty. Talked to Laszlo and he will look to see how he can fix his library.

**Comment by mtaghiza** [comment]
Fixed. Skyserver was reading the binary stream as a string. Changed it to read as a Byte array and now works. Will be working properly in the next release.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0
