### ISSUE TITLE
Invalid queries give runtime error rather than meaningful error message

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#49]
An invalid (presumably) query like:

SELECT TOP 10
   objid, ra, dec from phototag

drop table target
---------------

Returns a runtime error page (Server Error in '/SkyServer' Application with Web.config error info) rather than a meaningful error message to the user.

**Comment by thakar** [comment]
Note that this query is syntactically correct but just not a valid or permitted query.

**Comment by raddick** [comment]
What is a good error message to show the user, and under what circumstances should that error message appear?

Assigning to Ani to answer this question and/or discuss the issue further.

**Comment by thakar** [comment]
Jordan, I don't understand why you are creating all these secondary issues
and assigning them to the person who opened the issue (me). Clearly the
correct behavior in all these cases should be what the production skyserver
is already doing.  That is what the developer(s) should be trying to
reproduce in the WS version in the first place, isn't it?

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Courage is not the towering oak that sees storms come and go; it is
the fragile blossom that opens in the snow. [Alice M. Swaim]

**Comment by mtaghiza** [comment]
Fixed. Throws whatever error generated by casjobs, and produced by sql server trying to execute SpExecuteSQL, which has the query wrapped inside.
Correct behavior will show in next version.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0. Tested with this query:

`SELECT TOP 10
objid, ra, dec from phototag

drop table target`

Which returns this error message:

`Failed to execute a query: Cannot drop the table 'Target', because it does not exist or you do not have permission.`
