### ISSUE TITLE
adding a newline between SELECT and TOP causes query to be incorrectly parsed

### ISSUE THREAD

**Issue by capnsue** [idies/SkyServer#50]
in sql_search:

typing the following
SELECT 
TOP 10 *
FROM PhotoObj

causes query to fail with error message 

Msg 156, Level 15, State 1, Line 15
Incorrect syntax near the keyword 'top'.

This is because spExecuteSQL is rewriting the statement as 
select  top 500000 
top 10 * 
from photoobj 

It seems that the parser in spExecuteSQL is ignoring the "top" in the original query and adding another one

**Comment by thakar** [comment]
The version of spExecuteSQL currently on the production sites actually
checks if the user has included a "TOP n" clause and replaces the n with
the max n that is included as the @limit parameter to the procedure.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by capnsue** [comment]
Updated spExecuteSQL to replace CR (CHAR(13)) and LF (CHAR(10)) with spaces.  SQL does not care about newlines so this should be fine

**Comment by capnsue** [comment]
Ani -- yes,that's right -- the test version also includes a @limit of 500000 or something -- the problem was that the parser was ignoring the TOP when it came after a newline, so it was inserting another one, causing a syntax error.  This is fixed now.

**Comment by thakar** [comment]
Yes indeed, this is a bug even in the production sites if the "TOP n" is on
its own line (i.e. has a newline before it). Thanks!

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by capnsue** [comment]
I'll def include this fix in the patch for the production sites.

**Comment by thakar** [comment]
Awesome., thanks for finding and fixing this!

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
It always seems impossible until it's done. [Nelson Mandela]

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
