### ISSUE TITLE
Selecting all imaging columns and typical spectro columns in IQS returns runtime error

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#51]
Running s_imaging_query_form_12 test on the SkyServer Imaging Query Form (IQS) results in a runtime error that gives the error message "Server Error in '/SkyServer' Application." along with application error details that are hidden because of web.config settings.

**Comment by mtaghiza** [comment]
Fixed. It was an SkyserverWS problem. An issue with explanations was created in the SkyserverWS repository (what happens is that the response string becomes too long, surpassing the default limit).

**Comment by raddick** [comment]
This is a duplicate of #34. Filing as duplicate.
