### ISSUE TITLE
Proximity queries in IQS and SQS return runtime errors.

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#52]
Trying tests s_imaging_query_form_14, s_imaging_query_form_15 and s_imaging_query_form_16 to test the Proximity Search option in the Imaging Query Form (IQS) each results in runtime errors with the "Server Error in '/SkyServer' Application." error message.

**Comment by thakar** [comment]
Same problem for tests s_spectro_query_form_14 through _16.

**Comment by raddick** [comment]
Is this a duplicate of #33?

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Yes, this is a duplicate of #33, which is now fixed and verified.

Labeling this one as "duplicate" and closing.
