### ISSUE TITLE
Spectro Query Form (SQS) should show results in new tab.

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#53]
Unlike the other search tools including the Imaging Query Form (IQS), the Spectro Query Form does not create a new tab/window fo display the query results, so you have to use the browser back button to go back to your query page.

**Comment by mtaghiza** [comment]
Fixed. Correct behavior will show in next version.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0.
