### ISSUE TITLE
Higher than maximum row limit is ignored in imaging/spectro form queries

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#54]
If you enter a row limit above the maximum (500,000), say 9000000 in the "Limit number of output rows" in the Imaging or Spectro Query forms, the limit is ignored.  There is no error message and the query returns fine if the number of rows is modest. These are tests s_imaging_query_form_8 and s_spectro_query_form_8.

**Comment by raddick** [comment]
What message should we give to the user here?

**Comment by mtaghiza** [comment]
Works (maximum number of rows is 500000) except for the HTML format. 
It's giving this message:
Exception of type 'System.OutOfMemoryException' was thrown.

Will investigate where is it coming from.

**Comment by thakar** [comment]
Just tried it in imaging form query with 50000000 limit and it ran fine and the SQL query shown is:

SELECT TOP 50000000 p.run,p.rerun,p.camCol,p.field,p.obj FROM ..PhotoObj AS p JOIN dbo.fGetNearbyObjEq(10,0.2,5.0) AS b ON b.objID = P.objID

**Comment by mtaghiza** [comment]
Sorry Ani, I meant it works in the new version, which is going to be released next week.

**Comment by mtaghiza** [comment]
Seems that the HTML document being loaded is heavier than 260MB in his case. Apparently, this request is having problems with the proxy, since it runs fine when executed under scitest02.sdss.pha.jhu.edu/... , but returns a bad gateway error when executed under scitest02.pha.jhu.edu/...
We'll have to test this issue later in the production machines.

**Comment by raddick** [comment]
This was not being run through spExecuteSQL, but it needs to be run through at least through spExecuteSQL2 because it needs to be logged.

**Comment by thakar** [comment]
Fixed in v1_3_0
