### ISSUE TITLE
Large query output produces runtime error in spectro query form

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#55]
Specifying a huge output row limit and submitting a query (after selecting "no position constraint" option) in the spectro query form (test s_spectro_query_form_9) produces a runtime error "Server Error in '/SkyServer' Application." after several seconds.

**Comment by mtaghiza** [comment]
Fixed. Will be working properly in the next version.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0
