### ISSUE TITLE
The API section in the HELP web page contains mostly broken links

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#56]
See broken links in 

http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/api.aspx

(e.g., searching and explore sections)

This issue was brought up by looking at references of 'x_sql.aspx' in all Skyserver's code. This file does not exist any longer, so all links to it are broken.

We have to update the links according to the new methods/searches that we wrote.

**Comment by mtaghiza** [comment]
Fixed. Will show correct links in next release.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_4_0. Changed assignment to Manu, since he fixed it (thanks Manu!) and closing.
