### ISSUE TITLE
Object Crossid page missing/not implemented

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#58]
The "Object Crossid" page under Tools is missing, although you can get to it my directly typing the relative path "en/tools/crossid/crossid.aspx" in the URL window.  However, that page has not apparently been ported to the WS version.

**Comment by raddick** [comment]
Fixed but menu items need to be in consistent order (new issue).

**Comment by raddick** [comment]
The new issue was filed as issue #107.

**Comment by mtaghiza** [comment]
This issue is related to the fact that CrossID tool does query the database directly, instead of sending queries to casjobs. We have still to decide which way is going to be implemented at the end.

**Comment by mtaghiza** [comment]
Will create another clean issue about this.
