### ISSUE TITLE
Skyquery url is hardcoded in crossmatch.aspx page.

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#59]
This happens in crossmatch,aspx and crossmatch.js. These urls should probably be referring to the skyquery url definition in the web.config file.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by mtaghiza** [comment]
Please, test it by clicking on links of that URL in the crossmatch page.
(I already know that these are internally fixed)

**Comment by raddick** [comment]
The links work, so I declare these fixed.

The SkyQuery Cross-match tool does not work, but that's a separate issue.
