### ISSUE TITLE
Update contactUrl in globals

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#6]
The contact (help) URL now should be skyserver.sdss.org/contact, not skyserver.sdss3.org/contact.  Also the subject prefix for the helpdesk email should be [sdss] rather than [sdss3] (not sure if this is set up in SkyServer or in the contact page).

**Comment by mtaghiza** [comment]
Changed the helpdesk mail to sdss.org in the web.config file, and modified the ContactUrl in Globals.cs.
Closing...

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0 on 8/18/2015
