### ISSUE TITLE
SQL search form shows submitted SQL queries with extra "EXEC spExecuteSQL" preceeding them

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#60]
Shown as
EXEC spExecuteSQL + 'query' + ,'500000'

Better just to show 'query' instead.

**Comment by thakar** [comment]
Not sure where this is being shown/displayed, is this on the query output
page?

     Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Courage is not the towering oak that sees storms come and go; it is
the fragile blossom that opens in the snow. [Alice M. Swaim]

**Comment by mtaghiza** [comment]
Yes, on the html format. This also happens for the "search form" (both on scitest02's skyserver). Figured out how to show just the query; but will be included in the next release though.


________________________________

**Comment by raddick** [comment]
Manu, was this fix included in the sciserver_v1_1_0 release?

**Comment by mtaghiza** [comment]
no, it's for the next release.

**Comment by mtaghiza** [comment]
Fixed. Will be included in next version.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0
