### ISSUE TITLE
"Imaging" and "IR Spectra" titles missing from the HTML format result set in Radial and Rectangular Search

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#61]
They are present in the current production skyserver, but missing in the new one.

**Comment by mtaghiza** [comment]
Fixed. Will show up in next version.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0

Reassigned to Manu before closing so Manu gets the glory for implementing the fix. Thanks Manu!
