### ISSUE TITLE
QuickLook not showing the IAU style SDSS name of object

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#62]
The Quick Look page for SDSS objects does not display the SDSS (IAU-style) name for the object correctly at the top, it shows all zeros instead, e.g. SDSS J000000.00+000000.0 instead of SDSS J115837.74-002812.6 as shown on the Explore page.

**Comment by mtaghiza** [comment]
Fixed. it's a bug where the ra and dec where not initialized before passing them to the function that creates the IAU style name.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/quicklook/summary.aspx?
