### ISSUE TITLE
Failing to return 500000 rows in SQL Search tool.

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#64]
running the query 'select top 500000 objid from phototag' returns the following message from CasJobs:

Failed to execute a query: Query results exceed memory limitations. Please revise your query to return less information, or use MyDB

This happens also when using 'top 400000'.

As this seems to be a casjobs issue, posted it in the casjobs repository as well.

**Comment by mtaghiza** [comment]
Fixed. Mitya increased some memory-related variable in casjobs. Will show up correct behavior in next version.

**Comment by raddick** [comment]
That particular query now works, but a query that should return more columns still returns that same error.

Query:

`select top 500000 * from phototag`

Error message:

`Failed to execute a query: Query results exceed memory limitations. Please revise your query to return less information, or use MyDB`

I suppose we can't increase memory use indefinitely. And the error message above is fairly clear (I think?).

So I think we can close this, but I'm leaving it open and labeling as a question for now, so we can discuss.

**Comment by mtaghiza** [comment]
Yes, users should use MyDB for those kind of queries IMO.

**Comment by dmedv** [comment]
So... How big exactly do you want the limit to be (in MB)?

**Comment by raddick** [comment]
If you run the query referenced above:

`select top 500000 objid from phototag`

How big are the results in MB?

**Comment by raddick** [comment]
This error message is fine, we cannot avoid the memory exceeded message because casjobs cannot know a priori how big the query results will be.
