### ISSUE TITLE
SkyServer still directs to the old portal

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#65]
On the test SkyServer, it still directs to the old portal on scitest09 instead of Mitya's new portal on scitest02. 

Jordan is self-assigning, but if it's not a super-easy fix, I'll reassign to Manu.

**Comment by mtaghiza** [comment]
The release version (sciserver_v1.1.0) of the new login portal is not up and placed as the default login portal yet. SkyServer will by default direct to it anytime after this is done.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0 on 8/18/2015. Closing.
