### ISSUE TITLE
Search by 5-part SDSS ID in Navi name resolver

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#68]
Another request from Alex. In the Navigate tool name resolver, you used to be able to search by the 5-part SDSS ID (run-rerun-camcol-field-obj). That no longer works. Here is the link to the test site navi tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/explore/Summary.aspx

Please restore that search ability.

**Comment by mtaghiza** [comment]
Fixed. Will be included in next version for testing.

**Comment by raddick** [comment]
Doesn't appear to be working in sciserver_v1_2_0 . Tested by searching for this object:

6162-301-3-133-82

**Comment by mtaghiza** [comment]
It's working for me (explore opens object with objid=1237671939804561490)

**Comment by raddick** [comment]
Fixed in v1_2_0

**Comment by raddick** [comment]
And @mtaghiza has confirmed that the fix in the Explore tool was what Alex really wanted.
