### ISSUE TITLE
Navigate tool does not apply letter drawing options when SEARCH is clicked

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#69]
This is also a bug in the production (DR12) Navi tool. If you specify the drawing options as letters in the opt window, clicking on SEARCH only checks the appropriate buttons but does not redisplay the image with the proper overlay, you have to either change the zoom level or check/uncheck a drawing option for the letters to apply. In the Finding Chart, it works fine when you press "Get Image".

**Comment by mtaghiza** [comment]
Fixed. Now clicking on "get image" retrieves the new image. This fix needs testers to retest the whole navi page.

**Comment by raddick** [comment]
Awesome!

Tagged for testing in v1_3_0 starting Thursday 8/27.

**Comment by thakar** [comment]
Fixed in v1_3_0
