### ISSUE TITLE
Search by 5-part SDSS ID in Quick Look gives runtime error

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#71]
When you enter the test values for the 5-part SDSS ID in the Quick Look search by 5-part ID window, and click Submit, it throws a runtime error. The ID entered is: 5314-301-1-136-96. Also tried with a different one.

**Comment by mtaghiza** [comment]
Fixed. Will be included in next version fro testing.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0
