### ISSUE TITLE
Invalid values in all search boxes give runtime errors in Quick Look

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#72]
If you enter invalid values for objID, for ra,dec, for 5-part SDSS ID and for plate, mjd, fiber in the respective Search boxes in Quick Look, and press submit, all of them return a .NET runtime error page rather than a meaningful error message saying that the values are invalid.

**Comment by mtaghiza** [comment]
Fixed. Will be included in next version fro testing.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0
