### ISSUE TITLE
Search boxes in Explore, Quick Look etc. should be pre-loaded with default values

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#73]
If possible, search boxes for various types of searches in Quick Look and Explore should be filled in with default values, i.e. the values of the current object that is being viewed. This gives the user an example of what type of value is to be entered.

**Comment by mtaghiza** [comment]
Fixed. Will be included in next version for testing.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0
