### ISSUE TITLE
Sample SQL Queries point to outdated URLs for their execution in SQL Search query

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#74]
All queries in 

http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/realquery.aspx

are directed to the old URLs after clicking on "RUN QUERY"
Have to change them to the new URLs.

**Comment by mtaghiza** [comment]
Fixed. Will be working properly in the next version.

**Comment by raddick** [comment]
Fixed!
