### ISSUE TITLE
Invalid RA in Radial Search query throws a server error, not a meaningful error message

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#75]
When the RA is changed to 10000, there is an exception thrown with a stack trace and the following server error message:Response status code does not indicate success: 500 (There is some Internal Error Occured).

**Comment by mtaghiza** [comment]
This issue has been fixed; will be working correctly in the next version.

**Comment by raddick** [comment]
Verified as fixed in sciserver_v1_2_0
