### ISSUE TITLE
May want to switch to updated search box in QuickLook tool (like that in Explore tool)

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#76]
Right now, the quicklook tool has the old search menu, i.e., the individual objid or ra,dec , etc searches coming up in separate popup windows. We may want them to all appear in only one unified window above the metadata box, just like in the Explore tool.

**Comment by thakar** [comment]
Yes, definitely, given the other issues with the popup boxes, and they are
kinda' clunky anyway.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
No matter that patriotism is too often the refuge of scoundrels.
Dissent, rebellion, and all-around hell-raising remain the true
duty of patriots. [Barbara Ehrenreich]

**Comment by mtaghiza** [comment]
Fixed. Will be functional in the next release.

**Comment by raddick** [comment]
Looks good to me! Great job!
