### ISSUE TITLE
Review Explore tool queries.

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#77]
Don't know if it is possible to reduce the number of individual explore tool requests to Casjobs, since it is taking about 5-6sec to load the summary page. Will investigate this.

**Comment by thakar** [comment]
If we've decided to not route Explore (and other system queries) through
CasJobs in the future, then probably this is not spending time on right now.

   Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
No matter that patriotism is too often the refuge of scoundrels.
Dissent, rebellion, and all-around hell-raising remain the true
duty of patriots. [Barbara Ehrenreich]

**Comment by raddick** [comment]
Have we decided not to route system queries (e.g. queries generated by the Explore tool) through CasJobs? Where will we route them instead? Has this change been implemented yet?

**Comment by thakar** [comment]
No, this will be in a future version. We've decided to go back to the old
way of sending the system queries directly to the db server rather than via
casjobs WS.

  Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by raddick** [comment]
I'm confused. Ani, I'll come by your office to talk more about this.

**Comment by mtaghiza** [comment]
There are 17 queries that are sent to casjobs when the explore tool is loaded for the first time. As each query takes almost 0.3 seconds to complete, the explore tool takes about 5 seconds to load.

We decided instead to go back and use the direct connection to BestDR12 to run this queries. Also, it seems that a couple of queries can be merged into 1, e.g several queries have in common the join between PhotoTag or photoobj and specobj.

**Comment by mtaghiza** [comment]
Fixed. All queries go now directly into the database. Now the explore tool loads in 0.5-0.6 seconds. Please test thoroughly in next release.

**Comment by thakar** [comment]
Ah ok, I didn't realize that we had picked this option, I thought we were
going to throw an error.  I don't know what's more intuitive, maybe we
should check some other tools like NED, SIMBAD etc. to see what they do.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
There are three truths: my truth, your truth, and the truth.
[Chinese proverb]

**Comment by raddick** [comment]
It looks like it takes about 2 seconds for the Explore tool to load in the test environment. I think this is fixed. Closing.
