### ISSUE TITLE
Release tag missing/inconsistent in Skyserver's home page

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#78]
When hovering the mouse over right under privacy policy, it shows "heads/sciserver_vm..." instead of the version tag, e.g., DR12_v1.1.0

**Comment by mtaghiza** [comment]
Will have to checkout the tagged version.

**Comment by thakar** [comment]
It says DR12_v2.0.4 now, shouldn't it say DR12_v1_3_0?

**Comment by mtaghiza** [comment]
The DR12_v2.0.4 tag is consistent with the tag shown in the production website. The v1_3_0 is for the sciserver tag (sciserver-v1.3.0).

**Comment by raddick** [comment]
Works! Shows up on the site as:

```sciserver-v1.4.0-0-g00e7fc3
