### ISSUE TITLE
IR spectro search produces an empty FITS output file.

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#79]
Similar to #46

**Comment by mtaghiza** [comment]
The problem comes up when querying a column of type varchar, which cannot be handled correctly by the new fits library. Laszlo will look how to fix it.

**Comment by mtaghiza** [comment]
Fixed. Skyserver was reading the binary stream as a string. Changed it to read as a Byte array and now works. Will be working properly in the next release.

**Comment by thakar** [comment]
Great! But which release do you mean, v1_2_0 or the next one?

    Ani


--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by mtaghiza** [comment]
should be for next week, I already tagged this week's.

**Comment by raddick** [comment]
Verified as working in sciserver_v1_2_0
