### ISSUE TITLE
Auto-check checkboxes when values entered in associated textboxes

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#81]
This was discovered in the Radial and Rectangular search forms, but may be an issue in other forms too. Links to those forms:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/radial.aspx

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/rect.aspx

Look at the magnitudes section. When the user enters min/max magnitudes in those textboxes, s/he will expect those magnitudes to be added as query constraints. They are, but ONLY if you ALSO check the checkbox next to the textboxes.

That's very non-intuitive; many users will likely not realize and will wonder why their constraints aren't being applied.

Solution: when the user enters a value in one of the textboxes, the checkbox in that row should change to checked automatically.

**Comment by mtaghiza** [comment]
Fixed. Needs test in SciServer_v1_5_0 release.
