### ISSUE TITLE
Need error message for case of attempts to submit multiple SQL queries at once

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#82]
If you try to submit multiple queries at the same time in the SQL search tool with no semicolon separating them - e.g.

`select top 10 p.objid, p.ra, p.dec from photoobj p`

`select top 10 p.objid, p.ra, p.dec from photoobj p`

It returns only this vague and unhelpful error message, above the submitted SQL query:

`SQL returned the following error:`

Revise this error message so it conveys information to the user about why their query was not executed.

P.S. This issue grew out of issue #32, which has since been closed.

**Comment by raddick** [comment]
Just talked about this with Manu (@mtaghiza). It's not clear what to do in this case. spExecuteSQL has no way to recognize that the second query should not be run. In fact, running multiple queries one after the other is a *feature* of CasJobs that produces this unintended consequence now that we are running SkyServer queries through CasJobs.

We need to discuss this further with Ani (@thakar). Labeling as "talkmoreoffline" to remind us to have that discussion.

**Comment by thakar** [comment]
We (Manu and I) just figured out a way to disable multiple SELECTs in a
batch while still allowing nested SELECTs.  It requires some string jujitsu
in T-SQL, and Manu is going to implement it in the next version.
Basically, this will replace every un-nested SELECT after the first SELECT
by #SELECT, hence making the query invalid.

This is also a problem in the current production skyserver, so I can tack a
"select * from photoobjall" at the end of the first query, and it will
merrily execute the second query right after the first, and the results of
the first query will be held up while the second query is running.  SQL
Server apparently has no way to turn multiple statements off in a batch (we
looked).

        Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Maybe this world is another planet's hell. [Aldous Huxley]

**Comment by raddick** [comment]
Thanks! I'm labeling this as "missingfeature" to track it for fixing in the sciserver_v1_3_0 version.

**Comment by mtaghiza** [comment]
Fixed. Created the new spExecuteSQL in the database server. This is now adding a hash sign right before any second (and beyond) 'select' statement that is not in a nested query.
This is ready for testing right now.

**Comment by mtaghiza** [comment]
Maybe sue can patch again all other db servers with this new stored procedure when she's back.

**Comment by raddick** [comment]
Not working in sciserver_v1_4_0.

Go to the SQL Search tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/sql.aspx

Submit the following two-query query:

```
http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/sql.aspx
```

It returns an unhelpful error message saying:

SQL returned the following error: 
Failed to execute a query: Incorrect syntax near the keyword 'top'.

**Comment by thakar** [comment]
Your two links are the same (just point to the default sql query page), but
in any case, you cannot expect a more meaningful error message than this, I
think.  This is the syntax error that SQL Server returns (after
spExecuteSQL modifies the query), I believe, so there's no way to get
smarter than that.

       Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Men rarely (if ever) managed to dream up a god superior to
themselves.  Most gods have the manners and morals of a spoiled
child.  [Robert A. Heinlein]

**Comment by thakar** [comment]
It should really say "...syntax error near '#select'", not "near 'top'",  So that part needs to be fixed, but also we should manually replace '#select' with 'select', if possible.

**Comment by mtaghiza** [comment]
The error message cannot be changed since it comes directly from SQL server, and does not have a constant pattern to catch it..It is better to instead give a general error that warns the user about possible syntax errors and forbidden compound sql commands.
