### ISSUE TITLE
Add message to warn the user they are only getting the top 500,000 results

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#83]
When a user tries to return more than 500,000 results in a single query - e.g.:

`select * from phototag`

Our code adds a `top 500000`, and thus they only get 500,000 results.

This is the proper behavior, but we do need to warn the user that their results are being limited in a way they did not expect.

This should be a simple matter of adding a message at the top of the query, where we normally have the "SQL returned the following error" messages, saying something like this:

Too many results, showing only the top 500,000. To see complete results, run your query in CasJobs.

I know we do publish our query limits prominently in our documentation, but not everyone reads the documentation.

**Comment by mtaghiza** [comment]
I think the easiest solution is to explicitly write the max number of rows right besides its webform input box. Thus, there is no way the user will miss that piece of information

**Comment by thakar** [comment]
We should also prefix the query output with the following line:

Your query output (max 500,000 rows):
...

**Comment by mtaghiza** [comment]
Fixed. Needs testing for version  SciServer_v1_5_0.
