### ISSUE TITLE
Navigate: At largest Zoom levels, "Some Drawing Options..." message overlaps and is hard to read

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#84]
See screenshot.

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/9391568/712468e8-4745-11e5-8277-430b89d3ad10.jpg)

**Comment by mtaghiza** [comment]
No worries. This happens because the window width is small. Probably a standard-nowadays-screen (greater or at least equal than HD resolution) is wide enough to keep the login widget alone on the right side o the screen.

**Comment by mtaghiza** [comment]
Marking as "fixed". Should be closed by a tester in the next testing round.

**Comment by raddick** [comment]
Fixed
