### ISSUE TITLE
Navigate: Add a notification that name has been resolved

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#85]
When the user enters a name and clicks "Resolve," the coordinates of that object go into the ra/dec boxes, and then the user must click Search to see the object. The user may not notice that the coordinates have changed. So we should note to the user that the name has been resolved, and that they should click Search to see it.

**Comment by mtaghiza** [comment]
Fixed. Will work correctly in next version.

**Comment by raddick** [comment]
Fixed
