### ISSUE TITLE
"Add to notes" check mark is offset from "Add to notes" label

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#86]
When you click "Add to notes", a checkbox appears to tell you that your object has been saved to the notebook. The checkbox works, but its position is slightly offset from the words "Add to notes".

See the attached screenshot. 

![untitled-2](https://cloud.githubusercontent.com/assets/1709156/9392452/c3f7c6be-474a-11e5-8600-983f51de104a.jpg)

**Comment by mtaghiza** [comment]
Fixed. Will appear at right position in next version.

**Comment by thakar** [comment]
Fixed in v1_3_0
