### ISSUE TITLE
Navigate: Why do we hide specObj checkbox when highly zoomed out?

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#87]
I understand why we hide some drawing options at the most zoomed-out zoom levels - in particular the photometric objects checkbox, since that calls the photoPrimary table, which is huge.

But the "objects with spectra" checkbox looks for specPrimary instead, which is not nearly as big. Do we really need to disable that checkbox?

It's potentially helpful to have that option available at the most zoomed-out levels. That way, students can see how spectroscopic objects are confined to plates.

This is a question for the moment.

**Comment by mtaghiza** [comment]
I'm not sure the plate shape is going to show. Probably the displayed objects will be coming from the different plates that intersect the image field. Also, plates intersect each other as well.

**Comment by raddick** [comment]
Talked with @mtaghiza - it sounds like we really do need to hide the "specObj" option, since there are so many fields to draw things on at these outermost zoom levels. Closing the issue.
