### ISSUE TITLE
Image Cutout does not mark objects selected under the query option

### ISSUE THREAD

**Issue by mtaghiza** [idies/SkyServer#9]
Test ID=s_img_18
After clicking on the url, the resulting image shows no objects that have inverted triangles on top. Those triangles should be marking the objects selected by the query option. In this case, the query option is SR(10,20). Writing a SQL query on the query box does not work either.

**Comment by jkim485** [comment]
This is related to, and dependent on, the fix for #11.

**Comment by mtaghiza** [comment]
This problem is also related to failures of test s_chart_12 under the Chart tool.

**Comment by mtaghiza** [comment]
Solved by executing insert commands as a new user. Sue created the new script and user in the database server. We must make sure that these modifications are recorded somewhere and repeated for next releases.
