### ISSUE TITLE
RA, dec out of range error messages need to be updated

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#91]
Now that the RA, dec out of range errors are returning proper error messages, we should make sure that: 
a) we use "RA" (upper case since it is an abbreviation) instead of "ra" in the error message
b) we provide the complete valid range including units, i.e. instead of saying "ra must be less than 360", it should say "RA must be be between 0 and 360 degrees" and "dec must be between -90 and 90 degrees".

**Comment by thakar** [comment]
Error message has changed to "ra magnitude value must be between 0 and 360", this should really be "RA must be between 0 and 360"

**Comment by mtaghiza** [comment]
Fixed. Needs test in SciServer_v1_5_0 release.
