### ISSUE TITLE
Magnitude out-of-range error message needs to be less cryptic

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#92]
If the ugriz mags are out of range in the search tools, you get the error message (e.g.): Input parameter validation exception: u must be less than 35.  The first part has no meaning for the user, it should be dropped.  The error message (for both lower and upper boundary errors) should be the same and should just indicate the proper range, e.g. "u magnitude value must be between 0 and 35".

**Comment by mtaghiza** [comment]
Fixed. Better error messages will appear in next release.

**Comment by raddick** [comment]
Fixed in sciserver_v1_4_0
