### ISSUE TITLE
Make query row limit handling consistent across search tools

### ISSUE THREAD

**Issue by thakar** [idies/SkyServer#93]
Currently, some of the search tools (radial, rectangular, sql) ignore the row limit setting when it is higher than the preset limit (500k usually) and just tack on a SELECT TOP 500000 if the user specifies a limit higher than that.  However, the Imaging, Spectro and IR Query forms return an error if the user enters a limit higher than the max rows allowed.  We should pick one behavior (the error is what the production SkyServer returns) and make it consistent across all search tools.

**Comment by mtaghiza** [comment]
Fixed. An error message will appear when row limit > 500,000 in all those tools for next release.
