### ISSUE TITLE
Navigate: entering values in "opt" textbox does not update image

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#94]
In the Navigate tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/navi.aspx

Entering letters in the "opt" textbox - such as G, S, I, etc. - does check the boxes in the list of checkboxes below, but it does NOT update the image at all.

Screenshot below showing the effect of entering "I" and clicking "Search".

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/9414659/317a9c76-4808-11e5-8eef-8d0af5ead9a6.jpg)

**Comment by raddick** [comment]
Although it DOES work correctly on Internet Explorer 11

**Comment by raddick** [comment]
And on Chrome, Firefox, or Safari, an initial click on Search does not make the options appear on the image, but clicking on the zoom in/out buttons does make the options appear on the image.

**Comment by raddick** [comment]
And note that the equivalent options textbox DOES work on the Finding Chart tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/chartinfo.aspx

**Comment by raddick** [comment]
Same as #69

**Comment by raddick** [comment]
Note that the image should only be redisplayed when the user clicks Search.

**Comment by mtaghiza** [comment]
Fixed. Will be working int he next version. Testers will need to retest the whole navi tool.

**Comment by raddick** [comment]
Closing as a duplicate - keeping #69 open instead.
