### ISSUE TITLE
Navi/Chart: entering ra out of range mistakenly subtracts 360

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#95]
Go one of the chart-based tools, like the Navigate tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/navi.aspx

Enter an ra coordinate out of range, such as 9999. Click Search.

The tool should throw an error saying that the ra is out of range - or alternatively, should replace the bad ra value with (ra mod 360).

Instead, the tool subtracts 360 once, leaving the ra value likely still out of range. On IE 11, it instead subtracts 360 each time you click Search.

**Comment by mtaghiza** [comment]
Fixed. Will work correctly in next version.

**Comment by thakar** [comment]
Still a bug in v1_3_0, not working

**Comment by mtaghiza** [comment]
Searching for RA=9999 is wrapped around the sphere and gets you to RA=279. Let me know it is preferred a hard limit of RA=360 for RA>360 and RA=0 for RA<0.

**Comment by mtaghiza** [comment]
Fixed more carefully. Now the ra and dec values are wrapped around the sphere (and the user is warned about this), just as other online tools do it (e.g., NED). Please, retest this issue thoroughly and carefully. Note that ImageCutout in SkyServerWS was trying to implement the same wrapping, but seems that the code was not doing this correctly, so I replaced it with my new implementation. Will open an Issue for this in SkyServerWS.












Note that the ImageCutout code was not producing the correct wrap.

**Comment by raddick** [comment]
Fixed!
