### ISSUE TITLE
SQL Search tool: Errors should be reported as separate error messages outside of results

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#96]
In the SQL Search tool now, error messages are displayed in a query result box rather than a separate error message to the user. Filing this issue on behalf of @thakar , who pointed this out.

Example of how it looks now:

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/9415947/ade54704-4810-11e5-8fe1-64b5731f12ca.jpg)

Example of how we'd like it to look is what gets returned by the syntax check:

![untitled-2](https://cloud.githubusercontent.com/assets/1709156/9416001/0ec40e8e-4811-11e5-9b6e-8424cc2de92a.jpg)

**Comment by mtaghiza** [comment]
Fixed
