### ISSUE TITLE
Quick Look: Search for new object opens new window rather than tab in IE 11 & Safari 8

### ISSUE THREAD

**Issue by raddick** [idies/SkyServer#99]
Go to the Quick Look tool:

`http://scitest02.pha.jhu.edu/SkyServer/en/tools/quicklook/summary.aspx`

Click on "Search by... Objid" in the left-hand column. A small window pops up. Enter:

`1237663784205746244`

Click OK.

The new object appears in a new tab in most browsers, but as a new window in IE 11 and Safari 8.

Let's make the behavior consistent across browsers, if not too hard to fix.

**Comment by raddick** [comment]
Note that I've reported this using search by ObjID, but it occurs using all search options.

**Comment by mtaghiza** [comment]
This will no longer show, since this kind of search has been replaced by a search window as in the explore tool. Closing...
